### PR TITLE
fix: keep main feed scroll position on primary page navigation

### LINKED ISSUE #57: Go back from Notification to main feed, should remember main feed position scrollbar. Today it jumps to top.
Hi,

Go back from Notification to main feed, should remember main feed position scrollbar. Today it jumps to top.

Thanks.

### PR DESCRIPTION
**Pull request by DeMonkeyCoder**
fixes #57

I'm not sure why the ScrollArea component wasn't used for the small screens, but using this component fixed the persistent scroll behavior.

Please let me know if this shouldn't be used for mobile @CodyTseng

### CODE REVIEW

**Comment by CodyTseng** [comment]
> I'm not sure why the ScrollArea component wasn't used for the small screens, but using this component fixed the persistent scroll behavior.

If you use ScrollArea component. The browser treats it as a page with a fixed height, so certain default behaviors don’t work as expected when scrolling. For example, the address bar won’t auto-hide, and tapping the status bar won’t scroll the page to the top

**Comment by DeMonkeyCoder** [comment]
@CodyTseng

"address bar won’t auto-hide" I'm not sure which address bar you're talking about. Can you please send a screenshot?

Also tapping the "Notes" button from the top bar is still scrolling the page to the top in my branch. I played around with the UI and haven't noticed any change in the behavior.

Can you please provide more specific details?

**Comment by DeMonkeyCoder** [comment]
Fixed. Please review @CodyTseng

**Comment by DeMonkeyCoder** [comment]
> Hi, is this fixed on thread too? if not, I think it should. Thanks.

Yes. It should work exactly like the desktop version now.

**Comment by CodyTseng** [comment]
> Hi, is this fixed on thread too? if not, I think it should. Thanks.

Could you clarify exactly what the issue is?  Didn't get it from the video. 🤔

**Comment by CodyTseng** [comment]
> Open a thread, scroll the feed, click on a note inside the thread, click android back button. Should go back to the same position, but instead jump to the top.

Could you record a video? In the video you sent earlier, I didn't see the back operation. It seemed you clicked on the parent note instead. I don't think this issue actually exists. It works fine for me on iOS Safari

**Comment by CodyTseng** [comment]
I've taken a closer look, and the reason why the position of the main feed gets lost is mainly that when switching pages through the bottom navigation bar, the web page URL isn't modified, and the browser doesn't create a new page for rendering. As a result, the position information of the scrolling area gets lost. This issue can only be completely resolved by modifying the router of this project. It's a bit complicated, so I'll handle this problem myself. @DeMonkeyCoder

**Comment by CodyTseng** [comment]
> The bug exists and I did the android back button operation. I did this video now:

What will happen if you click the back button in the upper left corner?

**Comment by bitcoinuser** [comment]
> > The bug exists and I did the android back button operation. I did this video now:
> 
> What will happen if you click the back button in the upper left corner?

Nothing. The android back button only works at the bottom of the screen, not in the upper.

**Comment by CodyTseng** [comment]
> > > The bug exists and I did the android back button operation. I did this video now:
> > 
> > 
> > What will happen if you click the back button in the upper left corner?
> 
> Nothing. The android back button only works at the bottom of the screen, not in the upper.

I'm referring to this button.
image

**Comment by bitcoinuser** [comment]
> > > > The bug exists and I did the android back button operation. I did this video now:
> > > 
> > > 
> > > What will happen if you click the back button in the upper left corner?
> > 
> > 
> > Nothing. The android back button only works at the bottom of the screen, not in the upper.
> 
> I'm referring to this button. image

Ha ok, haha. But happens the same problem. Jump to top.

**Comment by CodyTseng** [comment]
> Ha ok, haha. But happens the same problem. Jump to top.

I suspect this is an issue with the browser. It seems to have performed a refresh operation. It's likely that due to excessive memory usage, the previous page was cleared by the browser.

**Comment by bitcoinuser** [comment]
> > Ha ok, haha. But happens the same problem. Jump to top.
> 
> I suspect this is an issue with the browser. It seems to have performed a refresh operation. It's likely that due to excessive memory usage, the previous page was cleared by the browser.

Hum, I don't think so. This doesn't happen if I'm on main feed, click to open a note and go back by Android back button.

**Comment by bitcoinuser** [comment]
I found another bug: If I open an image and click android back button, goes to main feed instead of to the note.

https://github.com/user-attachments/assets/277e80e5-f2f4-4bc9-8dd3-3e16f7d78343

**Comment by CodyTseng** [comment]
> Hum, I don't think so. This doesn't happen if I'm on main feed, click to open a note and go back by Android back button.

Then under what circumstances does this issue occur when pressing the back button? I've never encountered it on Safari.

**Comment by CodyTseng** [comment]
> I found another bug: If I open an image and click android back button, goes to main feed instead of to the note.

This isn't a new bug. It's the same issue as #16 and #126

**Comment by bitcoinuser** [comment]
> > Hum, I don't think so. This doesn't happen if I'm on main feed, click to open a note and go back by Android back button.
> 
> Then under what circumstances does this issue occur when pressing the back button? I've never encountered it on Safari.

If I click on a note, then click on a new note that is inside a thread.

**Comment by CodyTseng** [comment]
> If I click on a note, then click on a new note that is inside a thread.

Okay, there really is such an issue. If it's convenient for you, could you please create a separate issue for this problem?

**Comment by bitcoinuser** [comment]
> > If I click on a note, then click on a new note that is inside a thread.
> 
> Okay, there really is such an issue. If it's convenient for you, could you please create a separate issue for this problem?

Were you able to reproduce now?

**Comment by bitcoinuser** [comment]
> > Were you able to reproduce now?
> 
> Yes. It should have been fixed by now.

Yes, confirmed it was fixed. Thanks.

**Comment by DeMonkeyCoder** [comment]
I pushed a commit to fix the issue with JavaScript for now @CodyTseng

**Comment by bitcoinuser** [comment]
> I've taken a closer look, and the reason why the position of the main feed gets lost is mainly that when switching pages through the bottom navigation bar, the web page URL isn't modified, and the browser doesn't create a new page for rendering. As a result, the position information of the scrolling area gets lost. This issue can only be completely resolved by modifying the router of this project. It's a bit complicated, so I'll handle this problem myself. @DeMonkeyCoder

@DeMonkeyCoder what about this?

**Comment by DeMonkeyCoder** [comment]
> @DeMonkeyCoder what about this?

Well, it's probably gonna take a while, and for now this change can make people like @bitcoinuser happy. I can imagine that going to see a note's replies and then heading back to continue reading your feed but instead seeing that it's gone can be frustrating

File: src/layouts/PrimaryPageLayout/index.tsx [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { ScrollArea } from '@/components/ui/scroll-area'
 import { TPrimaryPageName, usePrimaryPage } from '@/PageManager'
 import { DeepBrowsingProvider } from '@/providers/DeepBrowsingProvider'
 import { useScreenSize } from '@/providers/ScreenSizeProvider'
-import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react'
+import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react'
```
Comment (CodyTseng) [inline src/layouts/PrimaryPageLayout/index.tsx:8]: 'useState' is defined but never used.

**Review by CodyTseng — APPROVED** [review]
Great solution! Thanks! Now I can procrastinate a little longer. 😄

File: src/layouts/PrimaryPageLayout/index.tsx (hunk 1 above)
Comment (DeMonkeyCoder) [reply src/layouts/PrimaryPageLayout/index.tsx]: fixed

**Comment by CodyTseng** [comment]
Ready to merge?
